<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>JustDraw.ico</ApplicationIcon>
    <AssemblyName>JustDraw</AssemblyName>
    <Version Condition="'$(Version)' == ''">0.0.0</Version>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="..\..\images\icon.png" Link="images\icon.png" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
